[package]
name = "slb9673_driver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitfield-struct = "0.5.2"
bitflags = "2.3.3"
hidapi = "2.4.1"
i2cdev = "0.5.1"
num-derive = "0.4.0"
num-traits = "0.2.16"
