name: Rust lint & test

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Crate
      uses: actions/checkout@v3
    - name: Set Toolchain
      # https://github.com/dtolnay/rust-toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: Run test
      run: cargo test
